### ISSUE TITLE
Periodically loses connection to OBS and requires reset

### ISSUE THREAD

**Issue by thedug** [BarRaider/streamdeck-obstools#7]
I've only noticed this after the machine goes to sleep, but the actions stop working and I have to go into the stream deck config and click the reset button on one of the OBS Tools actions. Then things work again.

Any tips on how to debug this?

**Comment by BarRaider** [comment]
Sounds like it looses connection to the websocket. You can try switching to a different Stream Deck profile and back which should attempt to reconnect.

**Comment by thedug** [comment]
Cool. I'll try that. 

Is there a place where I can watch that to see if there are errors or specific scenarios that are causing the connection to drop?

**Comment by BarRaider** [comment]
pluginlog.log in the plugin directory %appdata%\elgato\streamdeck\plugins
